version: "3"

services:
  api:
    build:
      context: ./api/docker/bun
      dockerfile: Dockerfile
    command: sh /app/start.sh
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    image: node:18-alpine
    container_name: web
    command: sh /app/start.sh
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
